# 主启动模块专有配置文件

# 数据源
spring:
  datasource:
    username: root
    password: u123456
    url: jdbc:mysql://localhost:3306/my_local_database?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  aop:
    auto: true
  session:
    store-type: redis
#  redis:
#    host: localhost
#    port: 6379

server:
  port: 8081
  servlet:
    context-path: /api/


